auto_paragraphs.auto_paragraph.*:
  type: config_entity
  label: 'Auto Paragraph'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    content_type:
      type: string
      label: 'Content Type'
    field:
      type: string
      label: 'Field'
    paragraph_field:
      type: string
      label: 'Paragraph Field'
    options:
      type: sequence
      label: 'Options'
      sequence:
        type: string
        label: 'Condition'
    paragraphs:
      type: sequence
      label: 'Paragraphs'
      sequence:
        type: string
        label: 'Paragraph'
